version: '3'

services:
  webapp:
    container_name: ${SRVICE_WEBAPP_INSTANCE}
    image: "${SRVICE_WEBAPP_INSTANCE}:${IMAGE_TAG}"
    build:
      context: ../
      dockerfile: ${DOCKER_WEBAPP_FILE}
    ports:
      - "${WEBAPP_PORT}:80"
    restart: unless-stopped
  server:
    container_name: ${SRVICE_SERVER_INSTANCE}
    image: "${SRVICE_SERVER_INSTANCE}:${IMAGE_TAG}"
    build:
      context: ../
      dockerfile: ${DOCKER_SERVER_FILE}
    ports:
      - "${SERVER_PORT}:3000"
    restart: unless-stopped
